apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-team-a
  namespace: team-a
spec:
  hard:
    pods: "4"
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 10Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-team-b
  namespace: team-b
spec:
  hard:
    pods: "4"
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi