apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-torino
  namespace: torino-tenant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-pod
  namespace: torino-tenant
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-torino
  namespace: torino-tenant
subjects:
- kind: ServiceAccount
  name: service-torino
  namespace: torino-tenant
roleRef:
  kind: Role
  name: read-pod
  apiGroup: rbac.authorization.k8s.io