apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-constraints
  namespace: tenant-b
spec:
  limits:
  - default: 
      cpu: 1000m
      memory: 50Mi
    defaultRequest: 
      cpu: 500m
      memory: 5Mi
    type: Container